//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsingGoogleMaps2.Models
{
    using System;
    using System.Collections.Generic;
    public enum Categories
    {
        Restaurant,Pub
    }
    public partial class Business
    {
        public Business()
        {
            this.EEVAs = new HashSet<EEVA>();
        }
    
        public int Id { get; set; }
        public int FK_Company { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<EEVA> EEVAs { get; set; }
    }
}
