//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsingGoogleMaps2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Businesses = new HashSet<Business>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Contact { get; set; }
    
        public virtual ICollection<Business> Businesses { get; set; }
    }
}
