//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsingGoogleMaps2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PubsDealsDBEntities : DbContext
    {
        public PubsDealsDBEntities()
            : base("name=PubsDealsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Business> Businesses { get; set; }
        public DbSet<Company> Companies { get; set; }
        public DbSet<EEVA> EEVAs { get; set; }
    }
}
