//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsingGoogleMaps2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal
    {
        public Deal()
        {
            this.DealEEVAs = new HashSet<DealEEVA>();
            this.Stats = new HashSet<Stat>();
        }
    
        public int Id { get; set; }
        public int FK_Pub { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public System.DateTime PublicationDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string DayOfWeeK { get; set; }
        public int VouchersForSale { get; set; }
        public int VouchersSold { get; set; }
    
        public virtual ICollection<DealEEVA> DealEEVAs { get; set; }
        public virtual Pub Pub { get; set; }
        public virtual ICollection<Stat> Stats { get; set; }
    }
}
