//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsingGoogleMaps2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pub
    {
        public Pub()
        {
            this.Deals = new HashSet<Deal>();
            this.PubEEVAs = new HashSet<PubEEVA>();
        }
    
        public int Id { get; set; }
        public int FK_Company { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public string Address { get; set; }
        public string Area { get; set; }
        public string LatLng { get; set; }
        public double DistanceTillAreaCenter { get; set; }
        public string ContactEmail { get; set; }
        public Nullable<double> NegotiatedPercentage { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<Deal> Deals { get; set; }
        public virtual ICollection<PubEEVA> PubEEVAs { get; set; }
    }
}
