//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsingGoogleMaps2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stat
    {
        public int Id { get; set; }
        public int FK_Deal { get; set; }
        public decimal PricePerVoucher { get; set; }
        public int VouchersForSale { get; set; }
        public int VouchersSold { get; set; }
        public System.DateTime PublicationDate { get; set; }
    
        public virtual Deal Deal { get; set; }
    }
}
